# Generated by Django 4.2.7 on 2026-03-06 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0003_alter_branding_title_whitelabel'),
        ('accounts', '0003_user_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='white_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branding.whitelabel'),
        ),
    ]
