# Generated by Django 4.2.7 on 2026-02-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IoT Energy Monitoring System', help_text='System title shown in headers and login', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Company logo (web and mobile)', null=True, upload_to='branding/')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
                'db_table': 'branding_branding',
            },
        ),
    ]
