# Generated by Django 4.2.7 on 2026-03-06 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branding', '0002_update_title_to_iot_monitoring_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='title',
            field=models.CharField(default='IoT Monitoring System', help_text='System title shown in headers and login', max_length=200),
        ),
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name (e.g. company name) used to identify this white-label.', max_length=120, unique=True)),
                ('title', models.CharField(default='IoT Monitoring System', help_text='System title shown in headers and sidebar', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='whitelabel/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whitelabels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'White Label',
                'verbose_name_plural': 'White Labels',
                'db_table': 'branding_whitelabel',
                'ordering': ['name'],
            },
        ),
    ]
