# Generated by Django 6.0.1 on 2026-01-27 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_key', models.CharField(help_text='Key sent by hardware (e.g., "v", "a", "pf")', max_length=50, unique=True)),
                ('ui_label', models.CharField(help_text='Display label in UI (e.g., "Voltage", "Current")', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., "V", "A", "kW")', max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameter Mapping',
                'verbose_name_plural': 'Parameter Mappings',
                'db_table': 'parameter_mappings',
                'ordering': ['hardware_key'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_address', models.CharField(help_text='5-digit hardware back-address (e.g., 465421)', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Hardware address must be exactly 5 digits', regex='^\\d{5}$')])),
                ('name', models.CharField(help_text='User-friendly name for the device', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_data_received', models.DateTimeField(blank=True, null=True)),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Users who have access to this device', related_name='assigned_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(help_text='JSON data from device (e.g., {"v": 230, "a": 5})')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Data',
                'verbose_name_plural': 'Device Data',
                'db_table': 'device_data',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['hardware_address'], name='devices_hardwar_f7c56a_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='devices_is_acti_9ea4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['area', 'building', 'floor'], name='devices_area_abac99_idx'),
        ),
        migrations.AddIndex(
            model_name='devicedata',
            index=models.Index(fields=['device', '-timestamp'], name='device_data_device__ac13fc_idx'),
        ),
        migrations.AddIndex(
            model_name='devicedata',
            index=models.Index(fields=['-timestamp'], name='device_data_timesta_28ab8a_idx'),
        ),
    ]
