# Generated by Django 4.2.7 on 2026-02-07 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_key', models.CharField(help_text='Hardware key (e.g. v, tkW)', max_length=50)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='devices.device')),
            ],
            options={
                'verbose_name': 'Threshold',
                'verbose_name_plural': 'Thresholds',
                'db_table': 'thresholds',
                'ordering': ['device', 'parameter_key'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_key', models.CharField(max_length=50)),
                ('parameter_label', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField(help_text='Limit that was breached')),
                ('type', models.CharField(choices=[('min', 'min'), ('max', 'max')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alarms', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='devices.device')),
            ],
            options={
                'verbose_name': 'Alarm',
                'verbose_name_plural': 'Alarms',
                'db_table': 'alarms',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='threshold',
            constraint=models.UniqueConstraint(fields=('device', 'parameter_key'), name='unique_device_parameter'),
        ),
    ]
