# Generated by Django 4.2.7 on 2026-02-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_add_threshold_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mqtt_broker_host',
            field=models.CharField(blank=True, help_text='MQTT broker host (e.g., localhost, broker.example.com)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_broker_port',
            field=models.IntegerField(default=1883, help_text='MQTT broker port (default: 1883)'),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_password',
            field=models.CharField(blank=True, help_text='MQTT broker password (optional, encrypted)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_tls_ca_certs',
            field=models.TextField(blank=True, help_text='TLS CA certificate path or content (optional)', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_topic_pattern',
            field=models.CharField(blank=True, help_text='Specific MQTT topic pattern for this device (e.g., EM/46521)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_topic_prefix',
            field=models.CharField(blank=True, help_text='MQTT topic prefix (e.g., EM, iot/devices)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_use_tls',
            field=models.BooleanField(default=False, help_text='Use TLS/SSL for MQTT connection'),
        ),
        migrations.AddField(
            model_name='device',
            name='mqtt_username',
            field=models.CharField(blank=True, help_text='MQTT broker username (optional)', max_length=255, null=True),
        ),
    ]
