# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_mqtt_broker_host_device_mqtt_broker_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hardware_address',
            field=models.CharField(
                help_text='Unique hardware identifier (e.g. 46542, device-id-01, MAC, etc.)',
                max_length=255,
                unique=True,
            ),
        ),
    ]
